Vagrant.configure('2') do |config|

    config.vm.define "development-VM2" do |subconfig|
      subconfig.vm.box = 'generic/centos7'

      subconfig.vm.synced_folder('.', '/vagrant', type: 'nfs', disabled: true)
      subconfig.vm.provider :vmware_esxi do |esxi|
      #  REQUIRED!  ESXi hostname/IP
      esxi.esxi_hostname = '192.168.0.39' 
      #  ESXi username
      esxi.esxi_username = 'provision'
      esxi.esxi_password = 'P@sswordP@ssword'
      #  SSH port.
      esxi.esxi_hostport = 22

      esxi.guest_name = 'development-node02'

  end
   
    config.vm.provision :chef_client do |chef| 
        chef.provisioning_path = "/etc/chef"
        chef.chef_server_url = "https://api.chef.io/organizations/diazdj"
        chef.validation_key_path = ".chef/diazdj.pem"
        chef.validation_client_name = "diazdj"
        chef.node_name = "Webserver01"
        chef.arguments = "--chef-license accept"
        chef.add_recipe "httpd_test::default"
   end
  end
  
  